[2024-04-09T07:25:56.881+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1120 manual__2024-04-09T07:25:46.617777+00:00 [queued]>
[2024-04-09T07:25:56.891+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1120 manual__2024-04-09T07:25:46.617777+00:00 [queued]>
[2024-04-09T07:25:56.892+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T07:25:56.907+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1120> on 2024-04-09 07:25:46.617777+00:00
[2024-04-09T07:25:56.913+0000] {standard_task_runner.py:60} INFO - Started process 2043 to run task
[2024-04-09T07:25:56.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1120', 'manual__2024-04-09T07:25:46.617777+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpytay2x6u']
[2024-04-09T07:25:56.920+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask 1120
[2024-04-09T07:25:57.153+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1120 manual__2024-04-09T07:25:46.617777+00:00 [running]> on host a1b04a9393da
[2024-04-09T07:25:57.222+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1120' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T07:25:46.617777+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T07:25:46.617777+00:00'
[2024-04-09T07:25:57.343+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'success', 'data': 'Sinh hoạt công dân - Định hướng Tân Sinh viên Khóa 18', 'message': 'Data already exists'}
[2024-04-09T07:25:57.360+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=1120, execution_date=20240409T072546, start_date=20240409T072556, end_date=20240409T072557
[2024-04-09T07:25:57.410+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T07:25:57.587+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
