[2024-04-09T23:55:03.395+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T23:40:40.894562+00:00 [queued]>
[2024-04-09T23:55:03.408+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T23:40:40.894562+00:00 [queued]>
[2024-04-09T23:55:03.409+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T23:55:03.425+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-09 23:40:40.894562+00:00
[2024-04-09T23:55:03.433+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-04-09T23:55:03.442+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'scheduled__2024-04-09T23:40:40.894562+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpgchisy5i']
[2024-04-09T23:55:03.446+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask 2112
[2024-04-09T23:55:03.963+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 scheduled__2024-04-09T23:40:40.894562+00:00 [running]> on host 083da196de81
[2024-04-09T23:55:04.044+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T23:40:40.894562+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T23:40:40.894562+00:00'
[2024-04-09T23:55:04.337+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.174958482}\''}
[2024-04-09T23:55:04.362+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240409T234040, start_date=20240409T235503, end_date=20240409T235504
[2024-04-09T23:55:04.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T23:55:04.701+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
