[2024-04-09T15:53:23.394+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T15:38:50.277723+00:00 [queued]>
[2024-04-09T15:53:23.412+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 scheduled__2024-04-09T15:38:50.277723+00:00 [queued]>
[2024-04-09T15:53:23.413+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T15:53:23.434+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-09 15:38:50.277723+00:00
[2024-04-09T15:53:23.446+0000] {standard_task_runner.py:60} INFO - Started process 124 to run task
[2024-04-09T15:53:23.458+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'scheduled__2024-04-09T15:38:50.277723+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp5el4luq_']
[2024-04-09T15:53:23.464+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask 2112
[2024-04-09T15:53:24.305+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 scheduled__2024-04-09T15:38:50.277723+00:00 [running]> on host dcb7ab325c84
[2024-04-09T15:53:24.408+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T15:38:50.277723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T15:38:50.277723+00:00'
[2024-04-09T15:53:24.725+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.207032525}\''}
[2024-04-09T15:53:24.759+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240409T153850, start_date=20240409T155323, end_date=20240409T155324
[2024-04-09T15:53:24.832+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T15:53:25.073+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
