[2024-04-09T12:26:02.808+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 manual__2024-04-09T12:25:51.350736+00:00 [queued]>
[2024-04-09T12:26:02.825+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 manual__2024-04-09T12:25:51.350736+00:00 [queued]>
[2024-04-09T12:26:02.825+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T12:26:02.849+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-09 12:25:51.350736+00:00
[2024-04-09T12:26:02.860+0000] {standard_task_runner.py:60} INFO - Started process 163 to run task
[2024-04-09T12:26:02.928+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'manual__2024-04-09T12:25:51.350736+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpx3q8p_mh']
[2024-04-09T12:26:02.950+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask 2112
[2024-04-09T12:26:04.343+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 manual__2024-04-09T12:25:51.350736+00:00 [running]> on host 4b0cf5e8e48f
[2024-04-09T12:26:04.540+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T12:25:51.350736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T12:25:51.350736+00:00'
[2024-04-09T12:26:05.002+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.139790054}\''}
[2024-04-09T12:26:05.118+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240409T122551, start_date=20240409T122602, end_date=20240409T122605
[2024-04-09T12:26:05.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T12:26:05.569+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
